version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: todosapp
      POSTGRES_USER: supermin
      POSTGRES_PASSWORD: supermin
